name: Build All Modules

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build (all projects)
        run: ./gradlew --no-daemon build
