name: Build All Modules

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build (all projects)
        run: ./gradlew --no-daemon build

  trigger-jitpack:
    name: Trigger JitPack build on tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger JitPack build for this tag
        env:
          TAG: ${{ github.ref_name }}
          REPOSITORY: ${{ github.repository }}
        run: |
          echo "Triggering JitPack build for $REPOSITORY:$TAG"
          URL="https://jitpack.io/com/github/${REPOSITORY}/${TAG}/build.log"
          echo "GET $URL"
          # Hitting the build.log endpoint triggers the build for public repositories
          curl -fsSL "$URL" | head -n 100 || true
