name: Release on Tag

on:
  push:
    tags:
      - 'v*'
      - 'release-*'

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Assemble (all projects)
        run: ./gradlew --no-daemon assemble

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v1.2.3
          tag_name: v1.2.3
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            **/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
