name: Release on Tag

on:
  push:
    tags:
      - 'v*'
      - 'release-*'

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Assemble (all projects)
        run: ./gradlew --no-daemon assemble

      - name: Derive release version
        id: derive
        shell: bash
        run: |
          REF="${GITHUB_REF_NAME}"
          echo "ref_name=${REF}" >> $GITHUB_OUTPUT

          BASE_VERSION="${REF}"
          IS_RETAG=false

          if [[ "$REF" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)(-.+)?$ ]]; then
            # Extract the numeric version without leading 'v'
            NUM_VER="${BASH_REMATCH[1]}"
            BASE_VERSION="$NUM_VER"
            # If there is a suffix (e.g., -2), mark as retag to force recreation
            if [[ -n "${BASH_REMATCH[2]}" ]]; then
              IS_RETAG=true
            fi
          fi

          echo "base_version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          echo "is_retag=${IS_RETAG}" >> $GITHUB_OUTPUT
          echo "Derived base_version=$BASE_VERSION from ref=$REF (retag=$IS_RETAG)"

      - name: Delete existing releases and tags if retag
        if: steps.derive.outputs.is_retag == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ steps.derive.outputs.base_version }}"         # e.g. 1.2.3
          REF_FULL="${{ steps.derive.outputs.ref_name }}"        # e.g. v1.2.3-1
          TAG_ORIG="v${BASE}"                                   # e.g. v1.2.3

          echo "Attempting to delete existing releases (if any)"
          # Delete releases associated with the original and the suffixed tags, if they exist
          gh release delete "$TAG_ORIG" -y || echo "No existing release $TAG_ORIG to delete"
          gh release delete "$REF_FULL" -y || echo "No existing release $REF_FULL to delete"

          echo "Checking and deleting remote tags if they exist"
          for TAG in "$TAG_ORIG" "$REF_FULL"; do
            if git ls-remote --tags origin | grep -F -q "refs/tags/${TAG}"; then
              echo "Deleting remote tag ${TAG}"
              git push origin :refs/tags/${TAG} || true
            else
              echo "No remote tag ${TAG} to delete"
            fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.derive.outputs.base_version }}
          tag_name: v${{ steps.derive.outputs.base_version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            **/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
